INSERT INTO `rex_square_shop_category` (`title`) VALUES ("Human Resources")
,("Accounting")
,("Advertising")
,("Asset Management")
,("Customer Relations")
,("Customer Service")
,("Finances")
,("Human Resources")
,("Legal Department")
,("Media Relations")
,("Payroll")
,("Public Relations")
,("Quality Assurance")
,("Sales and Marketing")
,("Research and Development")
,("Tech Support");